// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sailing_Rocks;

namespace Sailing_Rocks.Migrations
{
    [DbContext(typeof(SailingRocksContext))]
    [Migration("20210413154653_addedReview")]
    partial class addedReview
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sailing_Rocks.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LocatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RockId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lat = "41.52906515532968",
                            Lng = "-81.65136941810817",
                            LocatedOn = new DateTime(2021, 4, 13, 11, 46, 52, 885, DateTimeKind.Local).AddTicks(4527),
                            LocationImage = "https://media-cdn.tripadvisor.com/media/photo-s/14/61/c4/4f/lighthouse-at-headlands.jpg",
                            RockId = 1
                        });
                });

            modelBuilder.Entity("Sailing_Rocks.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RockId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "We found a rock.",
                            RockId = 1,
                            Title = "Sturdy"
                        });
                });

            modelBuilder.Entity("Sailing_Rocks.Models.Rock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 4, 13, 11, 46, 52, 885, DateTimeKind.Local).AddTicks(5),
                            Image = "https://thumbs.dreamstime.com/b/dwayne-johnson-80711565.jpg",
                            Name = "Dwyane",
                            Serial = "testSerial",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Sailing_Rocks.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hometown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Software Developer",
                            CreatedOn = new DateTime(2021, 4, 13, 11, 46, 52, 877, DateTimeKind.Local).AddTicks(6580),
                            Email = "jkepic19@gmail.com",
                            FirstName = "Jason",
                            Hometown = "Parma, OH",
                            Image = "https://jak719.github.io/images/HS5.png",
                            LastName = "Kepic",
                            Password = "password",
                            UserName = "jak719"
                        });
                });

            modelBuilder.Entity("Sailing_Rocks.Models.UserRock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RockId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RockId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRock");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RockId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Sailing_Rocks.Models.Location", b =>
                {
                    b.HasOne("Sailing_Rocks.Models.Rock", "rock")
                        .WithMany("Locations")
                        .HasForeignKey("RockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sailing_Rocks.Models.Review", b =>
                {
                    b.HasOne("Sailing_Rocks.Models.Rock", "Rock")
                        .WithMany("Reviews")
                        .HasForeignKey("RockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sailing_Rocks.Models.Rock", b =>
                {
                    b.HasOne("Sailing_Rocks.Models.User", "User")
                        .WithMany("Rocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sailing_Rocks.Models.UserRock", b =>
                {
                    b.HasOne("Sailing_Rocks.Models.Rock", "Rock")
                        .WithMany("UserRocks")
                        .HasForeignKey("RockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sailing_Rocks.Models.User", "User")
                        .WithMany("UserRocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
